name: Build Linux Artifacts
author: Minn

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl make cmake nasm gcc libssl-dev nlohmann-json3-dev doctest-dev

    - name: Bootstrap vcpkg
      run: native/libdave/cpp/vcpkg/bootstrap-vcpkg.sh

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Artifacts
      run: ./gradlew build -Ptarget=x86_64-unknown-linux-gnu
